services:
  openweathermap-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openweathermap-ui
    volumes:
      - "./apache/store-ui.conf:/etc/apache2/sites-available/000-default.conf"
      - "./app:/app"
      - "./.env:/app/.env"
    restart: always
    ports:
      - "80:80"
    networks:
      - web_app

  postgres:
    image: postgres:${POSTGRES_VERSION}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      timeout: 5s
      retries: 5
      start_period: 60s
#    volumes:
#      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - web_app

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

networks:
  web_app:
    driver: bridge